import Head from "next/head";
import { useState, useEffect } from "react";
import { useRouter } from 'next/router'
import { useAuth } from "../../context/AuthContext";
import Layout from "../../components/HubLayout";

import useSWR from 'swr'
import axios from 'axios'

export default function HubDashboard() {
  /* Auth */
  const { user, setUser } = useAuth();

  /* Get Page */
  const router = useRouter();
  const page = router.query.page ? router.query.page : 0;

  /* Fetch Data */
  const fetcher = (...args) => fetch(...args).then(res => res.json())
  const { data, error } = useSWR(`/api/hub/rankings?page=${page}`, fetcher)

  if (error) return <Layout><div className="p-5 text-xl text-white">failed to load</div></Layout>
  if (!data) return <Layout><div className="p-5 text-xl text-white">loading...</div></Layout>

  return (
      <>
        <Head>
          <title>Bloody ARK Hub</title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
            integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
            <div className="p-5 text-xl text-white">
            {JSON.stringify(data)}
            </div>
        </Layout>
      </>
  )
}
